### ISSUE TITLE
Transfer to JuliaMusic

### ISSUE THREAD

**Issue by Datseris** [jongwook/MusicProcessing.jl#3]
Hello,

do you think you could consider transferring this repo to [JuliaMusic](https://github.com/JuliaMusic)? We might be able to spend the appropriate effort to update it to latest stable Julia and increase the interplay with DSP.jl.

If you choose to transfer I'll add you as an owner of the repo.

**Comment by jongwook** [comment]
Hi, Thanks for the suggestion, and Kudos for maintaining JuliaMusic!

I'll be happy to transfer the ownership to JuliaMusic, as I don't have spare cycles to maintain this repo.

Let me know if you are ready, then I can use Github's function to transfer the ownership of this repo.

**Comment by Datseris** [comment]
Thank you for the positive response! I've invited you to join the org., so you can do the transfer anytime now.

**Comment by jongwook** [comment]
Great! I see an error when I try to transfer, because [JuliaMusic/MusicProcessing.jl](https://github.com/JuliaMusic/MusicProcessing.jl) already exists.

It seems like the repo is even with this one; could you delete the fork under JuliaMusic?

**Comment by Datseris** [comment]
Ops, sorry about that. I deleted it now.

**Comment by jongwook** [comment]
Done!
