### ISSUE TITLE
Consider register this package?

### ISSUE THREAD

**Issue by clouds56** [jongwook/MusicProcessing.jl#31]
Cannot be found on the General registry.

**Comment by ashwanirathee** [comment]
We are bringing it together with documentation and reviving code. But it will take some time before we register.

**Comment by clouds56** [comment]
What do you mean by reviving :)
I found that `mono(audio)` not working, saying "nchannels not defined".

**Comment by Datseris** [comment]
This package hasn't been updated in 4 years when we took over. If you want to help have a look at : https://github.com/JuliaMusic/MusicProcessing.jl/issues/10

**Comment by clouds56** [comment]
Great work! I could help fix some code update.

**Comment by Datseris** [comment]
closing in favor of #10
