### ISSUE TITLE
Update to Julia 1+

### ISSUE THREAD

**Issue by Datseris** [jongwook/MusicProcessing.jl#4]
There are many things to do here:

1. Add Project.toml files (very easy by just calling `Pkg.generate("MusicProcessing")`)
2. Update source.
3. Add tests.
4. Make tests Travis-only (test windows there as well).

**Comment by Datseris** [comment]
@ashwani-rathee  if you are interested in using your Librosa experience, this repo will need a bit of attention as well!

**Comment by ashwanirathee** [comment]
@Datseris ok!! I'll do that :)
