### ISSUE TITLE
Updating Music Processing

### ISSUE THREAD

**Issue by ashwanirathee** [jongwook/MusicProcessing.jl#6]
In Music Processing.jl
```jl
typealias Hertz SIUnits.SIQuantity{Int64,0,0,-1,0,0,0,0,0,0}
typealias Seconds{R} SIUnits.SIQuantity{R,0,0,1,0,0,0,0,0,0}
```

hey @Datseris what is to be done with this dead code??
They used SIUnits.jl which is no longer maintained and there is a new package called name Unitful.jl which combined a few of those pkgs and combines them together
(https://github.com/Keno/SIUnits.jl)
I believe here it is used to describe the meaning of Hertz
(http://painterqubits.github.io/Unitful.jl/stable/types/)I believe the very first is to be used for defining numeric type,dimensions and units

```jl
Quantities
# Unitful.Quantity — Type.
struct Quantity{T,D,U} <: AbstractQuantity{T,D,U}
A concrete subtype of Unitful.AbstractQuantity.

The type parameter T represents the numeric backing type. The type parameters D :: Unitful.Dimensions and U <: Unitful.Units
```

what will be the update??
```jl
struct Hertz{T,D,U} <: AbstractQuantity{Int64,S,-1}
struct  Seconds{R} <: AbstractQuantity{Int64,S,1}
```
it doesn't work really..

I need to update this also
```jl
#
# types used for fixed-point 16-bit and 32-bit encoding
#typealias PCM16Sample Fixed{Int16, 15}
#typealias PCM32Sample Fixed{Int32, 31}
#
```
which I did with:

#updated code
```jl
# types used for fixed-point 16-bit and 32-bit encoding
const PCM16Sample=Fixed{Int16, 15}
const PCM32Sample=Fixed{Int32, 31}
#
```

**Comment by Datseris** [comment]
I haven't read the library code yet, and won't have the time to contribute to this repo specifically for several months; too many things on my plate on other projects. I probably won't be much help for this repo. But my advice is: Is it necessary for this library to use Unitful? If not maybe you don't have to care about creating units for `Second` and `Hertz` and just use real numbers.

**Comment by jparcill** [comment]
Just an update on the direction I've been going in:

I've just been replacing Hertz and Seconds just for floats going for functionality first. 

Interestingly SampledSignals.jl already exports both Hz and s units from Unitful.jl.

That might be something we could look into later after the update.

**Comment by ashwanirathee** [comment]
Issue#10 continues on this discussion
